// Comments
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT';

// Article
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_FAILURE = 'EDIT_ARTICLE_FAILURE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';
export const CLEAR_SINGLE_ARTICLE = 'CLEAR_SINGLE_ARTICLE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const IS_LOADING = 'IS_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SET_PROFILE = 'SET_PROFILE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const SET_ALL_ARTICLES = 'SET_ALL_ARTICLES';
export const SET_LOADER = 'SET_LOADER';

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_MORE_ARTICLES_SUCCESS = 'GET_MORE_ARTICLES_SUCCESS';
export const GET_MORE_ARTICLES_FAILURE = 'GET_MORE_ARTICLES_FAILURE';
export const IS_LOADING_MORE = 'IS_LOADING_MORE';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';